services:
  students:
    image: students
    build:
        context: "./StudentAPI"
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - mongodb
    volumes:
      - mongodb:/data 
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb:/data   
  front:
    image: front
    build:
        context: "./Front"
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - students
volumes:
    mongodb: